### ISSUE TITLE
Add Cupy FFTs as FFTFilter option

### ISSUE THREAD

**Issue by PinkShnack** [RI-imaging/qpretrieve#10]
As described originally in #8, I want to add a Cupy and Cupy3d implementation for the FFTFilter.

### Prerequisites:
- [ ] Implement 3d array processing #9 

### Todos
- [ ] Add 2d and 3d cupy implementations
- [ ] Test to ensure the outputted FFT is identical.
- [ ] Add documentation (benchmarking etc)
